version: '3'

services: 
    api:
        container_name: api
        build: .
        command: yarn dev
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        environment: 
            NODE_ENV: 'development'
            PORT: 3000
            DB_MONGODB_NAME_TEST: 'api_planet_test'
            DB_MONGODB_NAME_DEV: 'api_planet'
            DB_MONGODB_ENDPOINT: 'mongodb://db'
            URL_SWAPI: 'https://swapi.dev/api/planets/'
            LOGGER_LEVEL: debug
        ports: 
            - '3000:3000'
        depends_on:
            - db
        links:
            - db

    db:
        container_name: mongodb
        image: 'mongo'
        volumes: 
            - ./data:/data/db
        ports: 
            - '27017:27017'